#SPDX-License-Identifier: MIT-0
---
# tasks file for sap_hana_bone_prepare
- name: 1. Ensure required prerequisite packages are installed
  ansible.builtin.package:
    name:
      - ansible-sap-install # required for the installation
      - lvm2                # required for the installation
      - unzip               # required for the installation
      - libatomic1          # required for HANA
      - libgcc_s1           # required for HANA
      - libstdc++6          # required for HANA
    state: present
    update_cache: yes # Ensure package manager cache is updated before installing

- name: 2. Ensure /etc/sysctl.conf file exists and has correct ownership
  ansible.builtin.file:
    path: /etc/sysctl.conf
    state: touch      # 'touch' creates the file if it doesn't exist
    owner: root       # Sets the owner to root
    group: root       # Sets the group to root
    mode: '0644'      # Sets permissions (read/write for owner, read for group/others)

- name: 3. Ensure /etc/init.d directory exists and has correct ownership
  ansible.builtin.file:
    path: /etc/init.d
    state: directory  # Ensures the path exists as a directory
    owner: root
    group: root
    mode: '0755'      # Standard permissions for system directories (rwxr-xr-x)

- name: 4. Ensure "{{ sap_hana_install_software_directory }}" directory exists and has correct ownership
  ansible.builtin.file:
    path: "{{ sap_hana_install_software_directory }}"
    state: directory  # Ensures the path exists as a directory
    owner: root
    group: root
    mode: '0755'      # Standard permissions for system directories (rwxr-xr-x)

- name: 4.1 Ensure "{{ sap_hana_install_software_extract_directory }}" directory exists and has correct ownership
  ansible.builtin.file:
    path: "{{ sap_hana_install_software_extract_directory }}"
    state: directory  # Ensures the path exists as a directory
    owner: root
    group: root
    mode: '0755'      # Standard permissions for system directories (rwxr-xr-x)

- name: 5. Ensure "{{ sap_bone_install_software_directory }}" directory exists and has correct ownership
  ansible.builtin.file:
    path: "{{ sap_bone_install_software_directory }}"
    state: directory  # Ensures the path exists as a directory
    owner: root
    group: root
    mode: '0755'      # Standard permissions for system directories (rwxr-xr-x)

- name: 5.1 Ensure "{{ sap_bone_install_software_extract_directory }}" directory exists and has correct ownership
  ansible.builtin.file:
    path: "{{ sap_bone_install_software_extract_directory }}"
    state: directory  # Ensures the path exists as a directory
    owner: root
    group: root
    mode: '0755'      # Standard permissions for system directories (rwxr-xr-x)

- name: Validate SAP HANA System ID - 'sap_hana_install_sid' is not in the list of reserved SAP SIDs
  ansible.builtin.assert:
    that: sap_hana_install_sid not in __sap_hana_install_sid_prohibited
    success_msg: |
      PASS: The SAP HANA System ID '{{ sap_hana_install_sid }}' is not in the list of reserved SAP SIDs in SAP note 1979280 v.20.
    fail_msg: |
      FAIL: The SAP HANA System ID '{{ sap_hana_install_sid }}' is in the list of reserved SAP SIDs in SAP note 1979280 v.20!

- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: _build
  register: temp_folder_info

- name: Use the temporary directory path
  ansible.builtin.set_fact:
    sap_bone_install_temp_dir: "{{ temp_folder_info.path }}"

- name: Set specific permissions on the temp directory
  ansible.builtin.file:
    path: "{{ sap_install_temp_dir }}"
    mode: '0700'
    owner: "root"
    group: "root"
  become: yes

- name: SAP HANA Pre Install, create parameters file
  ansible.builtin.template:
    src: "templates/hana_install.cfg.j2"
    dest: "{{ sap_install_temp_dir }}/hana_install.cfg"
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: SAP Business One Pre Install, create parameters file
  ansible.builtin.template:
    src: "templates/b1h_properties.j2"
    dest: "{{ sap_install_temp_dir }}/b1h_properties"
    owner: 'root'
    group: 'root'
    mode: '0600'
