#SPDX-License-Identifier: MIT-0
---
# tasks file for sap_hana_install
- name: Searching for the directory, containing hdblcm.
  find:
    paths: "{{ sap_hana_install_software_extract_directory }}"
    patterns: "hdblcm"
    recurse: yes
    file_type: file
  register: find_hdblcm_result

- name: Stop if tje sap_hana_install is missing
  ansible.builtin.fail:
    msg: "CRITICAL: The HANA installer hdblcm was not found."
  when: find_hdblcm_result.matched == 0

- name: Set the path as variable (Fact)
  set_fact:
    hdblcm_directory: "{{ find_hdblcm_result.files[0].path | dirname }}"

- name: Check the path
  debug:
    msg: "hdblcm was found in: {{ hdblcm_directory }}"

  #changed_when: true

- name: Start HANA installation
  block:
    - name: Install SAP HANA - {{ sap_hana_install_sid }} {{ sap_hana_install_number }}
      ansible.builtin.command: "./hdblcm --configfile={{ sap_install_temp_dir }}/hana_install.cfg -b"
      register: __sap_hana_install_job
      args:
        chdir: "{{ hdblcm_directory }}"
      async: 10800 # Seconds for maximum runtime, set to 3 hours
      poll: 0 # Seconds between polls, use 0 to run Ansible Tasks concurrently

    - name: Wait for the HANA Installation Job to finish
      ansible.builtin.async_status:
        jid: "{{ __sap_hana_install_job.ansible_job_id }}"
      register: __sap_hana_install_job_result  # <--- This holds the stdout/stderr
      until: __sap_hana_install_job_result.finished
      retries: 200
      delay: 30

  rescue:
    - name: Print failure message
      ansible.builtin.fail:
        msg: "HANA Installation failed! Checking logs in the always block..."

  always:
    - name: Report the command output
      ansible.builtin.debug:
        var: __sap_hana_install_job_result.stdout_lines
      when: __sap_hana_install_job_result.stdout is defined

    - name: Save output to a local file for auditing
      ansible.builtin.copy:
        content: "{{ __sap_hana_install_job_result.stdout | default('No output captured') }}"
        dest: "/tmp/__sap_hana_install_job_result{{ ansible_hostname }}.txt"
      delegate_to: localhost
      when: __sap_hana_install_job_result is defined
